name: Deploy Frontend

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Client Image
        run: docker build -t journey-client:latest .

      - name: Save & Compress Image
        run: |
          echo "📦 Saving client image..."
          docker save journey-client:latest -o client.tar
          gzip client.tar
          sudo chmod 644 client.tar.gz

      - name: Upload to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "client.tar.gz"
          target: "/root/app"

      - name: Load & Start Client
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/app
            
            gunzip -f client.tar.gz
            docker load -i client.tar
            
            # Update ONLY the client container
            docker compose -f docker-compose.prod.yml up -d client
            
            rm client.tar
            docker image prune -f
            echo "✅ Frontend Deployed!"